default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sephora_technical_test_development

test:
  <<: *default
  database: sephora_technical_test_test

production:
  <<: *default
  database: sephora_technical_test_production
